# Generated by Django 5.1.4 on 2024-12-19 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Register",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Full_Name", models.CharField(max_length=50)),
                ("Email", models.EmailField(max_length=254)),
                ("Phone_Number", models.IntegerField()),
                ("Course", models.CharField(max_length=50)),
            ],
        ),
    ]
